# Generated by Django 3.2.4 on 2021-07-01 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicleId', models.CharField(max_length=255, unique=True)),
                ('make', models.CharField(max_length=30)),
                ('model_name', models.CharField(max_length=30)),
                ('model_year', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=20)),
                ('nick_name', models.CharField(max_length=255)),
                ('modem_enabled', models.BooleanField()),
                ('vehicleAuthorizationIndicator', models.PositiveIntegerField()),
                ('serviceCompatible', models.BooleanField()),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
