# Generated by Django 3.2.4 on 2021-07-01 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veh', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carmodel',
            old_name='model_name',
            new_name='modelName',
        ),
        migrations.RenameField(
            model_name='carmodel',
            old_name='model_year',
            new_name='modelYear',
        ),
        migrations.RenameField(
            model_name='carmodel',
            old_name='modem_enabled',
            new_name='modemEnabled',
        ),
        migrations.RenameField(
            model_name='carmodel',
            old_name='nick_name',
            new_name='nickName',
        ),
    ]
