# Generated by Django 3.2.4 on 2021-07-03 05:54

from django.db import migrations, models
import fleetCommand.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FleetCommandModel',
            fields=[
                ('vehicleId', models.CharField(editable=False, max_length=255, unique=True)),
                ('uuid', models.CharField(default=fleetCommand.models.hex_uuid, editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('req_date', models.DateTimeField(auto_now_add=True)),
                ('ok_bySuper', models.BooleanField(default=False)),
                ('ok_byCustRep', models.BooleanField(default=False)),
                ('active_Req', models.BooleanField(default=True)),
                ('req', models.CharField(editable=False, max_length=255, unique=True)),
            ],
        ),
    ]
