# Generated by Django 3.2.4 on 2021-07-05 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleetCommand', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fleetcommandmodel',
            name='CustRep_Ok',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='CustRep_Ok', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fleetcommandmodel',
            name='Super_Ok',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Super_Ok', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fleetcommandmodel',
            name='initiated_byWho',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='initiated_byWho', to=settings.AUTH_USER_MODEL),
        ),
    ]
