# Generated by Django 3.2.4 on 2021-07-05 02:59

from django.db import migrations, models
import systemFord.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FordUptoDateModel',
            fields=[
                ('uuid', models.CharField(default=systemFord.models.hex_uuid, editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('req_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
