# Generated by Django 3.2.4 on 2021-07-03 05:54

from django.db import migrations, models
import systemFord.models


class Migration(migrations.Migration):

    dependencies = [
        ('systemFord', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forduptodatemodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='forduptodatemodel',
            name='uuid',
            field=models.CharField(default=systemFord.models.hex_uuid, editable=False, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
    ]
