# Generated by Django 3.2.4 on 2021-07-15 02:15

import carrental.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalModel',
            fields=[
                ('uuid', models.CharField(default=carrental.models.hex_uuid, editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('vehicleId', models.CharField(editable=False, max_length=10)),
                ('active_Rent', models.BooleanField(default=True)),
                ('req_date', models.DateTimeField(auto_now_add=True)),
                ('rental_length_days', models.CharField(max_length=4)),
                ('rental_by_phone', models.CharField(editable=False, max_length=10)),
                ('rental_mile_limits', models.CharField(max_length=6)),
                ('user_who_added', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_who_added', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
